tl-its-umich-edu/my-learning-analytics

- dashboard/cron.py
- dashboard/views.py
- mysql/init.sql
#245 .
This PR has one DB column update and cron job query update. Although it was not greatly needed but I felt it will be cleaner that way. 
Currently anybody who has uniqname can access the tool and who ever figured out the course_number can access all the Views student dashboard has to offer. This is not just true for Assignment view and this PR is not handling that. That would be a different Issue.
> #245 non-personalized view for assignments

- dashboard/static/js/assign-progress.js
- dashboard/static/js/controllers.js
- dashboard/templates/assignments.html
- dashboard/urls.py
- dashboard/views.py
This PR is addressing the assignment view backed call processing. instead of 2 separate calls to present assignment progress and plan view single DB query is doing it all. Now the Controller is handling both the data for the views. The Progress JS is loaded after assignment data call so that progress data is made available  
The `assign_progress.js` has a lot of white space changes in order to ignore the white space changes use the GitHub UI as show here
> single query to display both progress and plan view

- .gitignore
- Dockerfile
- README.md
- docker-compose.yml
- start.sh
- add gunicorn reload option for dev
- load local code changes into image (compose-file used `/code` but dockerfile was using `/dashbaord`. switch dockerfile to use `/code`)
- persist mysql container data
Related #121
> Improve docker dev environment

- .env.sample
- README.md
- dashboard/admin.py
- dashboard/common/db_util.py
- dashboard/cron.py
- dashboard/models.py
- dashboard/settings.py
- Each of the view options (files accessed, assignment planning, and grade distribution) can now be disabled globally via the VIEWS_DISABLED environment variable.
- If files accessed is disabled, will no longer attempt to collect data file date from Canvas Data or big query
- Admin course view options will hide disabled view options
- added default value of true for course view options
> Allows control over view options globally

- docker-compose.yml
static files are needed when `DEBUG=false`
Closes #405
> Fix docker compose prod mode

- NOTICE
Modified to `The University of British Columbia` and added link to UBC Learning Analytics website.
> Update NOTICE for UBC

- .env.sample
- dashboard/admin.py
- dashboard/common/db_util.py
- dashboard/cron.py
- dashboard/settings.py
- dashboard/templates/base.html
- docker-compose.yml
- Renames UDW to DATA_WAREHOUSE to be more data source generic
- adds env variable to disable unizin only features/data. Currently is this only the `unizin_metadata` table and the Canvas Data last update datetime (falling back unto last cron run for now)
- removes UDW environment variables from mysql container in docker compose file
> Support non-unizin Canvas Data sources

- .env.sample
- dashboard/admin.py
- dashboard/common/db_util.py
- dashboard/context_processors.py
- dashboard/models.py
- dashboard/settings.py
- dashboard/templates/base.html
- Switched from prefixing canvas ids to incrementing the id by a set integer from the `CANVAS_DATA_ID_INCREMENT` environment variable.
- This handles how Canvas Data creates their ids better
- DATA_WAREHOUSE_FILE_ID_PREFIX and DATA_WAREHOUSE_ID_PREFIX are removed (instead CANVAS_DATA_ID_INCREMENT is used)
Note: this is a breaking change to how `DATA_WAREHOUSE_ID_PREFIX` worked. Existing installation will need to update the value with the correct canvas id increment.
Depends on PR #349
> Refactor canvas id prefixing

- assets/src/containers/AssignmentPlanning.js
- assets/src/containers/GradeDistribution.js
The `GradeDistribution` page and `AssignmentPlanning` page shows error when `gradeData` or `assignmentData` is an empty object.
> Fix error when data is an empty object

- assets/src/containers/AssignmentPlanning.js
- assets/src/containers/FilesAccessed.js
- assets/src/containers/GradeDistribution.js
- assets/src/hooks/useFetch.js
- assets/src/service/api.js
In order to use mock objects for testing purposes, I had to abstract current API calls into separate functions. This will lead to a separate PR, which will use mock API calls (that will be stored with fake data in a `__mock__` folder) to test for react containers.
> Abstract api calls into api folder to allow for testing with mock calls

- assets/src/hooks/useFetch.js
Addresses https://github.com/tl-its-umich-edu/my-learning-analytics/issues/475.
`GET` is set by default, and the second parameter to `useFetch` can be used to pass `body` and `method` options to the [fetch api](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch).
> Expanded useFetch to support 'put', 'post', etc.

- assets/src/components/Histogram.js
- assets/src/components/createChartComponent.js
- assets/src/components/withResponsiveness.js
- assets/src/hooks/useCreateChart.js
- assets/src/hooks/useResponsiveness.js
Here's an example of converting higher-order components (HOCs) to hooks. I think it's easier to understand, and it also doesn't cause unnecessary component nesting (since each HOC component adds a new layer of nesting). 
Let me know what you think! 
Happy to rewrite the rest of the React D3 components so they use hooks instead of HOCs.
> Added equivalent hooks to HOCs

- assets/src/components/d3/createHistogram.js
Currently Grade Distribution chart is using two different font types. This is an attempt to standardize the font type used across all graphs.
> standardize all fonts in graph

- README.md
- dashboard/settings.py
- dashboard/templates/base.html
solves #523 
- This PR solves the issue of adding Copyright information in the footer using Django [flatpages](https://docs.djangoproject.com/en/1.11/ref/contrib/flatpages/) from Django admin view.
- The requisite seems to agree on a flatpage url currently I have it as `copyright`
- Django Flatpages can provision creating static pages like `/about/` but I took the approach of getting the flatpage content to be populated inside of the template. More info [here](https://docs.djangoproject.com/en/1.11/ref/contrib/flatpages/#getting-a-list-of-flatpage-objects-in-your-templates)
- Currently, I have the instance of this code running on https://dev-myla.tl.it.umich.edu/ for review process.
> Adding copyright text using django flatpages

- assets/src/containers/DashboardAppBar.js
When `My Learning Analytics: {Course Name}` is clicked, it routes to `localhost:5001/{course code}` instead of `localhost:5001/courses/{course code}`. This PR resolves this issue.
> Correctly route to index page when app bar name is clicked

- package.json
The Node Package Manager (NPM) warned of security warnings during the build phase of docker, so I updated the dependencies, which got rid of nearly all the warnings (and all of the high and medium level vulnerabilities). 
To test, please rebuild your docker: `docker-compose up -d --build`.
I tested and everything seemed to be working as normal.
> Updated dependencies, resolved security warnings

- Dockerfile
- start.sh
The wait-port wasn't working anymore to stop the startup until database starts up, seems easier to just drop that and use netcat.
> Fixes #589 switch wait-port over to netcat

- dashboard/views.py
Adding the resource type attribute to the Event_logs. This is how it looks
```
{
"week_num_start":2,
"week_num_end":4,
"grade":"All",
"course_id":17700000000298053,
"resource_type":[
"Files",
"Videos"
]
}
```
> adding new resource type to event logs

- assets/src/containers/Course.js
- assets/src/containers/GradeDistribution.js
This PR makes modifications to `GradeDistribution.js` and `Course.js` to resolve issue #628. The following changes have been made:
1) The checkbox color for "Show my grade" has been changed to blue (`primary`) to be consistent with with "Resources Accessed" view.
2) A conditional operator was added so that the "My grade" row of the sidebar table disappears and appears (toggles) with the line above the histogram.
3) A conditional operator was added so that the "Show my grade" checkbox only appears when the user is not an admin. Determining a user's admin status required passing the user from the `Course` container to the `GradeDistribution` container as part of `props`.
4) To enhance the readability of the `Grid` being returned from `BuildGradeView`, two new variables -- `tableRows` and …
> Resolving issue 628: checkbox color, grade toggling, admin handling

- assets/src/components/d3/createResourceAccessChart.js
The X-axis for the resources view is broken the bars percent don't get reflected in the x-axis percentage. 
Expected: 
Current:
> xaxis should reflects based on % from data than always showing  0-100

- dashboard/views.py
Fixes #643 
The issue here is for course that doesn't have student grades in a particular range < 80 and a request from UI comes for that, we just need to recognize that and just return with an empty response. If this is not caught leading to Exception which we want to avoid
Course: 295223
> #643 adding a check for no students in a particular grade range

- .env.sample
- README.md
- dashboard/settings.py
- docker-compose.yml
- start.sh
I think this is a better idea than the current suggestion of copying in the secrets. I'll update the documentation in another commit.
> Fixes #653 map a secrets directory for easier addition of secrets

- dashboard/lti.py
- dashboard/settings.py
Noticed that `rules.permissions.ObjectPermissionBackend` was interfering with the LTI login (ObjectPermissionBackend doesn't have a get_user function) since it is the first auth method listed after the permissions update. Switching to explicitly using the `django.contrib.auth.backends.ModelBackend` backend (and making sure its a backend available if lti is enabled)
> Fixing LTI to explicitly use ModelBackend

- dashboard/graphql/objects.py
- dashboard/graphql/query.py
- dashboard/graphql/schema.py
- dashboard/settings.py
- dashboard/urls.py
- requirements.txt
Login & course permissions are checked in the query root course and courses fields (and therefor propagate down)
Currently this only exposes courses, discussions (topics & messages), and a limit user view (just user_id and name) for discussions.
This will be expanded after discussion NLP is completed to fetch those results
Part of #623
> Add basic GraphQL endpoint

- assets/src/components/AvatarModal.js
- assets/src/containers/Course.js
- assets/src/routes/routes.js
- dashboard/models.py
This issue fixes the `files access` text that remained after the rename to `resource access`. 
I see that My Learning Analytics Help is still hardcoded to umich one(https://sites.google.com/umich.edu/my-learning-analytics-help/home), not sure if different universities want to have their own Help doc. But the content present in the doc is suitable for all universities.
> Remove remaining code referencing files accessed view

- dashboard/models.py
- dashboard/views.py
This PR adds additional logic to the `get_course_date_range` method of the `Course` model to more elegantly handle the case when a `Course` instance has no values for `term`, `date_start`, or `date_end`. In practice, this enables an administrator or developer to view the `/courses` page or any of the views before running `cron.py` (which populates the `term` field of the `Course` instance). The PR aims to resolve issue #665.
Specifically, the changes to `models.py` mean that if `date_start` and `term` are null for a `Course` instance, `get_course_date_range` will return the value of `datetime.datetime.now(pytz.UTC)`. If `date_end` and `term` are null, then `get_course_date_range` will return a DateTime indicating the time two weeks after the course's start (i.e., either the value of …
> Adding fallback dates to get_course_date_range

- assets/src/components/AvatarModal.js
- assets/src/containers/App.js
- dashboard/templates/base.html
The help URL is now configurable through the Django admin page. Help URLs can now be changed by adding a flat page with the url set as /help_url/ and the content set as the desired url for the help page.
Closes #688.
> Configurable Help URL Through Django Flat Pages

- README.md
- dashboard/settings.py
- start.sh
Allow loading settings from a JSON encoded environment variables instead of only by json file. This helps support certain deployment situations where it might be hard/impossible to mount a file into the container
> Add ENV_JSON settings support

- assets/src/components/d3/createHistogram.js
- assets/src/containers/GradeDistribution.js
- dashboard/views.py
This is the case when all the grades are binned eg [60,70,90, 100, 100, 100, 100, 100, 100, 100]. in this case, the highest binned grade would be 100 and low grader like 60% will be but in the 100% bin and this would be bad. So in case of binning all the grades just show the normal distribution.
I think We need to come up with a better design for preserving outlier but that we can tackle in next releases.
> Grades binning all case so just show Normal distribution

- dashboard/common/utils.py
- dashboard/context_processors.py
- dashboard/settings.py
- dashboard/templates/base.html
- start.sh
This PR modifies and adds to existing code to expose information to superusers about the Git code version currently in use, specifically the commit and branch. These details are now gathered through git commands in the `start.sh` script, hopefully making the feature available in various environments and across institutions. The code has been tested and appears to be working as expected both locally and deployed to the development instance of MyLA. More details on the changes are provided below. The PR aims to resolve issue #698.
1) Previously, information about the build and Git source was accessed using environment variables only available when running the application in an OpenShift container/pod. After some discussion, we decided the build info was not strictly necessary, and that …
> Displaying git version info in footer for superusers (#698)

- config/env_sample.json
- dashboard/cron.py
- dashboard/models.py
- dashboard/settings.py
This PR includes a modification to the `update_term` method of `cron.py` to bring in all term records available from the Unizin Data Warehouse, as well as some changes to the handling of term dates in the `get_course_date_range` method. See below for additional explanation and details. The PR aims to resolve issue #758.
1) Previously, the terms fetched were limited (using a `WHERE` clause) to those before an `EARLIEST_TERM_DATE` specified as an environment variable. Removing this clause brings in terms earlier than the date previously specified, as well as terms without dates, (e.g. "No Term" or "Default Term") to the local database.
2) Because some of the new terms pulled using `cron.py` do not have dates, I added some additional handling to the `get_course_date_range` method of the …
> Fetching all terms using cron (#758)

- config/env_sample.json
- dashboard/admin.py
- dashboard/management/commands/site.py
- dashboard/models.py
- docker-compose.yml
- start.sh
This PR makes changes to the Django back-end and `start.sh` in order to provide convenient links in the Django admin to course landing pages in the MyLA front-end. Besides making changes to `models.py` and `admin.py`, I created a new environment variable `LOCALHOST_PORT` and added a new management command `site` so that the domain could be set automatically through `start.sh`. I have tested this locally and on [the MyLA development instance](https://dev-myla.tl.it.umich.edu), where the changes are still deployed (as of the morning of 10/14). More details on the changes are provided below. This PR aims to resolve issue #684.
1) Adding a "View on Site" link to the Course edit page and a field link in the Course list view was relatively straightforward. The former was created automatically …
> Adding links to courses in the Django admin (#684)

- assets/src/components/UserSettingSnackbar.js
- assets/src/containers/Course.js
- assets/src/containers/GradeDistribution.js
- assets/src/containers/SideDrawer.js
- assets/src/hooks/useSetUserSetting.js
Resolves #705 
The cause was subtle, caused by putting the `UserSettingSnackbar` component within the `buildGradeView` function. This means that every time GradeDistribution rerenders (including any time that the side drawer is opened), a _brand new_ instance of the  `UserSettingSnackbar` component is created, which causes the `useEffect` function within the component to lose track of state, making it render every single time instead of checking the dependency array. 
Took forever to debug 😂
> Fix snackbar sidedrawer issue

- assets/src/components/d3/createResourceAccessChart.js
This PR addresses the issue in the Resource Access view where the tool tips currently say "read" which  does not make sense for videos or other types of resources that are not read. This PR changes the text to "accessed." 
Closes #724
> Changed tooltip text in resource accessed view

- Dockerfile
- package.json
Fixes #790 
I just need to update the `node-sass` dependency to [14.12](https://github.com/sass/node-sass#supported-nodejs-versions-vary-by-release-please-consult-the-releases-page-below-is-a-quick-guide-for-minimum-support) as that is the support version for Node 12. Webpack-watcher behavior doesn't seem to be affected. I put this build on [Dev](https://dev-myla.tl.it.umich.edu/) instance seems to work fine.
> updating node to version 12

- assets/src/components/AvatarModal.js
- assets/src/containers/App.js
- assets/src/containers/CourseList.js
- dashboard/common/db_util.py
- dashboard/context_processors.py
- dashboard/settings.py
- dashboard/templates/base.html
- dashboard/views.py
This PR moves the construction of the `myla_globals` object from the `base.html` template to the `get_home_template` function view of `views.py` in order to fix a bug involving improper handling of apostrophes and streamline the appearance of `base.html`. Some other changes were made to simplify or clarify the process of generating a list of courses a user is enrolled in. More details will be forthcoming. The PR aims to resolve #779.
1) The majority of this PR is focused on moving the code and logic constructing a `myla_globals` dictionary or object from `base.html` to the `get_home_template` view. The dictionary can be constructed within the function view, serialized to a JSON string via `json.dumps`, and then passed via `render`'s `context` parameter to the template (see [this …
> Moving myla_globals construction to views.py (#779)

- Dockerfile
Fixes #788 
It looks likes these packages are pulled out from this image [`python:3.6`](https://github.com/docker-library/python/blob/22b2cebaaee699c43f4eb70c732be92ad4bf098e/3.6/buster/Dockerfile) and no update on that base image with security fixes. 
So doing the `apt-get upgrade -y` pulled in the latest version of those packages.
Build Output pulling the latest version:
```
The following packages will be upgraded:
file libfribidi0 libmagic-mgc libmagic1
4 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 490 kB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 http://security.debian.org/debian-security buster/updates/main amd64 file amd64 1:5.35-4+deb10u1 [66.4 kB]
Get:2 http://security.debian.org/debian-security …
```
> #788 security fixes

- assets/src/containers/Course.js
Hi, me and @luctiger have been working on this bug fix so that we could make an open source contribution for our 481 class. The proposed change makes it so that a user will see helpful error messages if they try to access a course that does not exist (404) or a course that they do not have permission to view (403). A different message is displayed for each error. Here are the error messages:
> Supplies better error message if the course doesn't exist (#670)

- assets/src/containers/GradeDistribution.js
- dashboard/views.py
The grade distribution API used to send a full dataframe. This PR changes it so that a simplified JSON string is sent instead of a full dataframe. This JSON string follows this format:
```
{ 
"summary":{ 
"current_user_grade": XX.X,
"tot_students": XX,
"grade_avg": XX.X,
"median_grade": XX.X,
"show_number_on_bars": false,
"show_dash_line": true,
"graph_upper_limit": XX.X
},
"grades":[XX.X, XX.X, ...]
}
```
This PR addresses and closes issue #707.
> Simplified API Format for Grade Distribution View (#707)

- assets/src/components/UserSettingSnackbar.js
Advised from PR #815 
Changed according to the suggestion : "Fade in (or slide in) for 200-400ms for saccade time for the eye to refocus, then show for 200ms for each of the characters in the message." for issue #806. 
Also give the duration time a minimum value 4000ms.
Also added role=alertdialog.
> Update snackbar visualization time for issue #806 from branch issue-806-fix-snackbar-duration

- dashboard/views.py
This PR makes a small change to the `grade_distribution` view in `views.py` to fix a bug that was causing grade counts not to show on histogram bars when "Show Grade Counts" was checked in the Django admin. I fixed a conditional statement that was assigning `True` as the value associated with a key `show_number_on_bar` so that instead it updates an existing property "show_number_on_bars" that was initialized as `False`. The PR aims tor resolve #851.
> Fix typo in grade_distribution view (#851)

- assets/src/components/d3/createResourceAccessChart.css
- assets/src/components/d3/createResourceAccessChart.js
This PR changes the d3 component `createResourceAccessChart` so that the resource labels and icons are a standard link blue (#0000EE). Previously, when these were uncolored, we observed inconsistencies between how browsers colored these elements (Firefox treating them as links, Chrome just coloring them gray). This PR aims to resolve issue #830. Thanks to @vjcao for creating the issue and giving me tips on resolving it.
> Re-color resource links for consistency across browsers

- assets/src/components/d3/createProgressBar.js
- assets/src/components/d3/createResourceAccessChart.js
- assets/src/defaultPalette.js
- config/env_sample.json
This PR makes some changes to the color palette used by the front end's `siteTheme`, based on work done by @jennlove-um. The  default `primary` color  was changed to better match UM's integration with Canvas (note that the `primary` after PR #845 is configurable through `env.json`). The `secondary` and `negative` colors were modified to maximize contrast between them (which is still below where we'd like it to be, at 3.03) while also maintaining adequate contrast between the `negative` gray and the white background. I also modified the `d3` components for the visualizations in Resources Accessed and (the old) Assignment Planning so that text on bars is white when the background color is `secondary` (blue) and black when the background color is `negative` (gray). This PR aims to resolve …
> Modify palette colors and visualization text colors to improve contrast (#748, #805)

- dashboard/cron.py
This short PR changes the `SELECT` query from `course_dim` in `cron.py` so that it only retrieves the values of fields needed by the update processes. This PR might resolve issue #864, but the presence of "error" in log output may not have caused past failed builds (recent cron runs had this "error" string and still succeeded).
> Specify needed fields in course select query (#864)

- dashboard/cron.py
This PR fixes an error we were encountering after merging PR #868 that was caused by unexpected conversion of `None` values to `NaT` values when concatenating DataFrames in the `verify_course_ids` method in `cron.py`. The change to the condition in `update_datetime_field`, with the use of `pd.isnull`, should handle cases of `None` and `NaT`. The PR aims to resolve issue #870.
> Replace not None check with pd.notna in update_datetime_field

- assets/src/__tests__/d3/__snapshots__/createHistogram.test.js.snap
- assets/src/globals.js
Responding to changes from PR #845, this PR adjusts `globals.js` to use an empty object if it is unable to find the`myla_globals` JSON element in the DOM. Along with an extra condition checking whether `mylaGlobals.primary_color` is `undefined` allows tests to import and consume `siteTheme` without an error. I also updated the hex values in the snapshot for `createHistogram.test.js` to reflect the new secondary color from PR #853. This PR aims to resolve issue #874.
> Add fallback empty object for mylaGlobals and update createHistogram test (#874)

- requirements.txt
This PR modifies some version ranges in `requirements.txt` to ensure minor version release updates are allowed for trusted dependencies (specifically, with Django) and that version ranges are normalized (using realistic and consistent patterns). The PR aims to resolve issue #897.
The changes here resulted in only these differences from the test instance (which is built off the `2020.01.x` branch).
```
< Django==2.2.9
---
> Django==2.2.10
35c35
< jsonfield==2.0.2
---
> jsonfield==2.1.1
```
> Correct version ranges in requirements.txt (#897)

- assets/src/components/d3/createResourceAccessChart.js
- assets/src/containers/CourseList.js
- assets/src/defaultPalette.js
This PR changes the logic in the `CourseList` container so that all users not enrolled in a course with MyLA enabled have the same user experience (regardless of whether they are a superuser or not). Providing an alternative to the somewhat confusing results detailed in issue #785, these changes make it so all unenrolled users see an `AlertBanner` informing them of the application state and linking to the help page. To incorporate the help page link with the rest of the application, I also updated the `defaultPalette` to include a standard link blue and updated hardcoded uses of this color elsewhere in the application. Note that the link color in the `AlertBanner` seems to change to purple when clicked (I saw this behavior in Firefox, Chrome, and Safari). The PR aims to resolve issue …
> Provide unenrolled users with better feedback, add link color to palette (#785)

- assets/src/components/d3/createResourceAccessChart.js
- assets/src/containers/ResourcesAccessed.js
- assets/src/hooks/useResponsiveness.js
This PR makes significant changes to the Resources Accessed view to make spacing more consistent and the charts and text respond appropriately to changing window sizes. It accomplishes this by introducing percent-based calculations of component sizes and coordinates, removing the use of a `Grid` component wrapper, and truncating text based on pixel length. The task list and commentary below provide more details on the changes. The PR aims to resolve issue #694.
Note that this PR does not fix all current issues with the view, but hopefully it makes strides toward improving the user experience in general and making it easier for developers to change things quickly with less potential for bugs.
Regarding the new `truncate` method, I have seen some discussion on forums and in blogs suggesting …
> Make Resources Accessed resize gracefully, re-work spacing (#694)

- dashboard/admin.py
- dashboard/common/utils.py
- dashboard/cron.py
- dashboard/models.py
- dashboard/urls.py
- dashboard/views.py
* This changes the two methods in the model for Course to a property so they can be more directly accessed.
* It also sorts the objects by this value so the object id can be re-used later.
* It also has a rename of dashboard in the cron as we don't need to see that in the logs anymore
> Fixes #873 - Display course in cron where earliest found

- assets/src/containers/IndexPage.js
Tabbing through the Index Page will not make users press tab twice to traverse to next button. This PR addresses issue #907.
> Smoother Keyboard Traversing of Buttons on Index Page

- dashboard/migrations/0014_add_auto_field_to_resources.py
- dashboard/migrations/0015_auto_20200116_1408.py
This issue is ordering the migration files so that assignment redesign migration  file comes last in order to support a release for 2020.1.x with fix #918 which doesn't include the assignment redesign course
> I918 reordering migration files

- assets/src/components/d3/createResourceAccessChart.js
This PR fixes #913 by changing multiplying the `dy` value by -1 in the `scroll` function when creating the chart in `createResourceAccessChart.js`.
> reverse scrolling direction for resource view

- assets/src/containers/CourseList.js
This PR address #921 by giving the `<Link>` element in `CourseList.js` a tabIndex value of -1.
> Smoother CourseList Keyboard Navigation

- assets/src/containers/SideDrawer.js
This PR aims to remove the ambiguity between selected and current view button in the sidebar. Fixes issue #896.
> Changed Selected Button Behavior in Sidebar

- assets/src/containers/CourseList.js
- assets/src/containers/SideDrawer.js
- assets/src/defaultPalette.js
This PR updates usages of the custom colors `negative` and `link` in the theme's palette so that they directly access the hex values through `siteTheme.palette.{color}.main` instead of through `color={color}`, which results in console warnings. The comments in `defaultPalette.js` were updated to reflect this. The PR aims to resolve issue #930.
It seems like we'll have to wait for Material UI 5 for full custom color support.
> Avoid warnings by using siteTheme.palette.negative.main, palette.link.main (#930)

- dashboard/models.py
This PR makes a minor modification to `dashboard/models.py` to re-enable a "View on Site" button available from the "Change Course" page in the Django admin. This seems to have been lost in an earlier PR when `get_absolute_url` (which has special meaning to Django) was changed to a `@property` implementation with `absolute_url`. The fix here merely re-creates the `get_absolute_url` method and leverages the aforementioned property. The PR aims to resolve issue #936 
"Change Course" admin page with change:
The course referenced above is fabricated.
> Bring back "View on Site" on "Change Course" page (#936)

- assets/src/components/AssignmentTable.js
- assets/src/util/assignment.js
Resolves #881.
I was able to reproduce the bug - it's caused by rounding as you suspected @ssciolla. 
I fixed by rounding to one decimal when the numbers are displayed in `AssignmentTable`. I also had to round in `assignment` because every time the state changes, GraphQL needs to store the floats and I was getting an error from GraphQL that the floats were too large - I decided to round to 3 decimal places for the internal state, which resolves the rounding error.
> Fixed rounding bug

- assets/src/containers/Course.js
- dashboard/rules.py
- dashboard/urls.py
- dashboard/views.py
- requirements.txt
Resolves #985.
Accepts JSON payloads in the request body of the format:
```json
{
"ap": { "enabled": true },
"apv1": { "enabled": false },
"gd": { "enabled": true, "show_grade_counts": true },
"ra": { "enabled": true }
}
```
Where each of the root-level keys are optional, but at least one must be given.  The `enabled` key is required for any object given.  The `show_grade_counts` key for the `gd` object is optional.  If it is not given, that option won't be updated.
The "jsonschema" module is used for input validation.
Of the four items listed in the requirements for #985, I've not yet tested whether non-instructors are disallowed from using this new API entry.
I'm unsure under which conditions this API entry will be used, so I'm not sure whether the Django model updating code I used …
> API to support course config settings (#985)

- dashboard/admin.py
- dashboard/cron.py
This PR modifies the existing `update_term` and `update_course` cron methods so that only new terms are added to the database, and existing terms are not updated. It also adds an Admin view for `AcademicTerms`, only allowing users to edit the start and end dates. Additionally, the changes include some unrelated improvements to `update_course` and a function it uses, `soft_update_datetime_field`, to make the code clearer and more generally useful. The PR aims to resolve issue #963.
> Enable term management, improve cron methods (#963)

- dashboard/graphql/loaders.py
- dashboard/graphql/view.py
- requirements.txt
This PR aims to resolve #952. This PR has dependency on this [PR](https://github.com/tl-its-umich-edu/my-learning-analytics/pull/997) related to Graphene-django update
As part of LTI 1.3 update Django version is updated to 3. But this PR is aiming to update all the latest version pip package.
Certain packages don't have an update since couple of years. I feel either we have to revisit then for alternatives
Pinax-eventlog library had an latest release of 4.0.1 and update to that break for Mysql as migration file is incorrect for mysql more on that [here](https://github.com/pinax/pinax-eventlog/issues/32).
> I952 package update to latest 

- config/env_sample.json
- dashboard/cron.py
Resolves #826.
I scrapped the approach I had been taking and started fresh.
Rather than trying to combine UDP and Kaltura API data using a new technique of my own, I decided to re-use the existing UDP-only approach and adapt it to work with MiVideo events.  The efficiency I thought my technique would bring probably wouldn't save as much resources as I expected.
The strange thing about this when I test it is that I see many messages logged to the console that say rows with various resource names and IDs are being updated, but when the process is done and I check my DB contents, I don't see any of that.
~Also, I've been testing with my personal test course in production Canvas (https://umich.instructure.com/courses/374350).  The course has several test students and they've all viewed the …
> #826 - load MiVideo usage data from UDP

- dashboard/admin.py
- dashboard/common/db_util.py
- dashboard/cron.py
- dashboard/settings.py
- mypy.ini
This PR adds a `mypy.ini` file specifying the Python 3.8 version and fixes mypy errors currently flagged by running `mypy` on the command line. An error flagged in a migration file was ignored. This PR aims to resolve issue #1027.
> Fix current mypy issues in dashboard (#1027)

- dashboard/cron.py
This PR creates a new instance variable on `DashboardCronJob` that is used for storing the course IDs verified by the initial `verify_course_ids` method. This variable is then used in lieu of `Course.objects.get_supported_courses`, because this list is static (while users could add new courses during the cron run, which would be returned by `get_supported_courses` or other `QuerySet` at other points of the run). The PR aims to resolve issue #1062.
> Lock list of course IDs driving other cron methods after verification (#1062)

- dashboard/views.py
Without the fix, I can repeat the problem by going to MyLA courses and open Assignment Planning view.
The SettingWithCopyWarning is a type of Pandas warning message, and [there are ways to fix the warning](https://www.dataquest.io/blog/settingwithcopywarning/). This fix is to get a copy of dataframe object first before further operations.
> issue-1070: operate on dataframe copy to prevent Pandas SettingWithCopyWarning warning

- dashboard/management/commands/createkeys.py
- requirements.txt
Resolves #1066.
Adds `createkeys` command to Django management tools.  Includes a `--basename` option to allow the user to specify a name for the key files generated.  If no base name is specified, a timestamp of the format `%Y%m%d%H%M%S` is used by default.  It produces three key files in the configuration directory, with the suffixes `_private.pem`, `_public.pem`, and `_public-jwk.json`.
When called as:
```sh
python manage.py createkeys --basename tarfu
```
It produces files named `tarfu_private.pem`, `tarfu_public.pem`, and `tarfu_public-jwk.json`.
> add key generation management command (#1066)

- assets/src/containers/Course.js
Set alt text via title on CardMedia element.
I tested using the [ChromeVox](https://chrome.google.com/webstore/detail/chromevox-classic-extensi/kgejglhpjiefppelpmljglcjbhoiplfn?hl=en) chrome extension.
By default I (Windows) had to press Shift+Alt+A Shift+Alt+A to toggle ChromeVox on and off.  Shift+Alt is the "Chrome Vox Key" and is different on different platforms. On MacOS its Control+Command, per the documentation.
Navigating to the image (I clicked on it) triggers the text to be read aloud.
> Add alt text for mouse on wheel loading image (#1082)

- dashboard/common/db_util.py
Closes #1061 
This eliminates a warning message for admin users.
I believe this situation can only occur in standalone.
> Elimiate an unnecessary warning message for admins

- assets/src/containers/App.js
- assets/src/containers/AssignmentPlanning.js
- assets/src/containers/AssignmentPlanningV2.js
- assets/src/containers/Course.js
- assets/src/containers/GradeDistribution.js
- assets/src/containers/ResourcesAccessed.js
- package.json
Closes #957 
This might turn out to be irrelevant with changes for LTI but leaving this PR here in case.
This updates the title when you brows between courses/course/view in standalone mode, but does not change the title in LTI mode (at least in the case of Canvas, where it remains the LTI tool's name.)
> Update title when navigating site

- assets/config/lti_config_template.json
- config/env_sample.json
- dashboard/lti_new.py
- dashboard/settings.py
- dashboard/urls.py
Resolves #1054.
I'm working on wiki docs for this new feature.
More testing details in the issue, #1054. 
1. Go to Canvas' LTI Developer Key creation page:
* https://umich.instructure.com/accounts/1/developer_keys#lti_key_modal_opened
1. In the "Method" menu, select the "Enter URL" item.
1. Copy the following URL and paste it into the "JSON URL" field:
* https://nnnnnnnnnnnn.ngrok.io/lti/config/
* Replace "nnnnnnnnnnnn" with the ID number of your ngrok server.
1. Copy the following URL and paste it into the "Redirect URIs" field:
* https://nnnnnnnnnnnn.ngrok.io/lti/launch/
* Replace "nnnnnnnnnnnn" with the ID number of your ngrok server.
1. (Optional, recommended) Enter meaningful values into the "Key Name", "Owner Email", and "Notes" fields.
1. Click the "Save" button.
> Implement LTI config by URL (#1054)

- assets/src/components/d3/createResourceAccessChart.js
Closes #797 
When pressing the tab key you can now navigate down the list of resources
1. Resource Name 1 (Screen reader will read file name "Some File.pdf")
2. Resource Bar 1 (Screen reader will read "Some File.pdf has been accessed by 37% of students.")
3. Resource Name 2
4. Resource Bar 2
etc.
> Keyboard navigation enabled for resource % bars

- assets/src/util/assignment.js
#1125 
The missing of the current and Max grades was happening with certain assignment doesn't had points meaning points = 0 or null (no point at all). I can say sometime instructor creates these assignments as a reading assignments or for attendance purposes. The progress bar is not considering those assignments in those cases
> #1125 fixes missing current and Max grade line for AssignV2

- assets/src/components/SelectCard.js
Closes #1123 
Just removes the default padding at the bottom of the element so the presence of the info icon doesn't expand it's enclosing element downward.
> i-icon compress the text

- .vscode/launch.json
- start.sh
Really just removed the quotes from gunicorn. With the exec it was causing it to expand to single quotes when not set and this is always either set to a specific variable or unset so safe.
Also setting it to reload now if debugging is on.
> Fixes #1108 - Problem starting up when not setting GUNICORN_RELOAD

- assets/src/__tests__/components/d3/__snapshots__/createHistogram.test.js.snap
- assets/src/components/d3/createHistogram.js
- assets/src/components/d3/createResourceAccessChart.js
- assets/src/index.css
This PR modifies class names and SVG `line` and `text` classes to improve contrast on axes in the Grade Distribution and Resources Accessed views. All ticks, text, and lines should be black, with the exception of the gray horizontal lines in the Grade Distribution, which @jennlove-um and I agreed may disrupt the visualization if they were black. The PR aims to resolve issue #802.
> Make axis lines, ticks, and text black (where appropriate) (#802)

- assets/src/components/StyledTextField.js
- assets/src/defaultPalette.js
This PR adds a `warning` color to the `defaultPalette` for use in the Assignment Redesign (specifically for the `StyledTextField`). Because `warning` is a standard color in Material UI (see [Palette](https://material-ui.com/customization/palette/)), it can be used with the `color` prop or `withStyles(theme => ({})...`. I conferred with @jennlove-um on the hex value choices; the `dark` variant is used for the text to ensure it meets W3C contrast requirements but fits with the `main` variant used in the outline and bottom line. The PR aims to resolve issue #878.
Note: the `info` color in the palette is also a shade of orange. We will be separately assessing whether it makes sense to modify that value for consistency/clarity.
> Introduce warning color to theme palette, use in StyledTextField (#878)

- assets/src/components/AssignmentTable.js
Fixes #1156.
With recent [merges](https://github.com/tl-its-umich-edu/my-learning-analytics/commit/58242d02003ec79c7ed7b85cd115e740e3e1c6a5) I see this issue is happening. I did not create another issue but tagged as part of 1156
```
react_devtools_backend.js:2430 Warning: Failed prop type: Invalid prop `children` of type `array` supplied to `RootRef`, expected a single ReactElement.
in RootRef (created by AssignmentTable)
in AssignmentTable (created by WithStyles(AssignmentTable))
in WithStyles(AssignmentTable) (created by AssignmentPlanningV2)
in div (created by AssignmentPlanningV2)
in div (created by AssignmentPlanningV2)
in div (created by ForwardRef(Paper))
in ForwardRef(Paper) (created by WithStyles(ForwardRef(Paper)))
in WithStyles(ForwardRef(Paper)) (created by …
```
> #1156 removing the warning message

- assets/src/components/SelectCard.js
This PR modifies the underlying element of the `Typography` component of the help doc links so it uses a `p` element instead of `h4`. The `h4` may pose accessibility issues because of skipped header levels, and it doesn't really accurately capture the purpose of the link. The styling is maintained because `variant='h5'` remains on the component. The PR aims to finish resolving issue #807.
See Typography API, `component`: https://material-ui.com/api/typography/
> Make Typography component in help docs link appear as p tag instead of h4 (#807)

- assets/src/components/AssignmentGoalInput.js
- assets/src/containers/AssignmentPlanningV2.js
This PR modifies the header that accompanies the course goal input on the Assignment Planning view (redesign). It also moves the header out to the view container, to be consistent with the other headers on the page and give a better sense of the page flow from the component. The PR aims to resolve issue #1179.
> Change "My Minimum Goal" to "My Minimum Goal (%)" (#1179)

- assets/src/components/AssignmentTable.js
- assets/src/components/ProgressBarV2.js
- assets/src/hooks/usePopoverEl.js
This PR presents a functional, if imperfect, solution that allows users to view the `PopUpMessage` content when an assignment-specific progress bar is navigated to using a keyboard. It is "imperfect" in the sense that there is a visual bug where if the user scrolls or uses the up or down arrow key when a bar is focused and the pop-up is visible, the pop-up will keep its position in the entire window and move away from the bar. @jennlove-um thinks this partial solution may be acceptable for now, and we can continue to refine it going forward. These changes include a `usePopoverEl` custom hook to reduce some duplication between the `onFocus` and `onBlur` handlers and the mouse-over handlers. The PR aims to resolve issue #800.
> Show PopUpMessage with assignment-specific progress bars when navigated to by keyboard (#800)

- package.json
This also fixes #1184 
Built with 
`docker-compose build --no-cache`
> Update webpack and webpack-cli to latest 4.x versions

- start.sh
Can instead pass GIT_REPO, GIT_COMMIT, and GIT_BRANCH as environment variables instead of requiring an active git repo to pull info
> Make git check optional

- dashboard/common/utils.py
- dashboard/templates/base.html
This PR follows up on PR #1204 to better handle the case in the UI of when no Git variables are provided. Ultimately, `GIT_REPO`, `GIT_BRANCH`, and `GIT_COMMIT` need to be defined as environment variables; if they are not, the template will not show that block of info in the footer. This is a minor improvement building on top of @andrew-gardener's work. The PR aims to resolve issue #1236.
> Handle lack of Git environment variables better in util function and template (#1236)

- dashboard/views.py
Week "1" in the UI actually starts at `timedelta(0*7)` rather than `timedelta(1*7)`
> Fixes #1289 Off by one error in start date calculation

- assets/src/components/d3/createResourceAccessChart.js
This PR aims to resolve #1298.
I don't know exactly the cause of this error, the scrolling stuff in this `d3` component is confusing to me. However the errors seem to go away when it's removed, and I didn't see any differences in the view. The change could use some testing though, and I think @justin0022 and @pushyamig worked on this code last.
I am still seeing a warning message in the console saying "[Violation] 'wheel' handler took 947ms", but it seems to be happening with or without this change, so it seems to be NOT related.
> Remove `d3.event.preventDefault` to resolve console errors in Resources Accessed (#1298)

- docker-compose.yml
- webpack.config.js
Is anyone else on any platform seeing this issue? 
Maybe it's just because I have "Use gRPC FUSE" unchecked? I'll try to restart with that checked.
Okay it's only seems like this is an issue if that option is unchecked.
> Fixes #1293 - Webpack doesn't seem to be reloading the frontend

- dashboard/admin.py
- dashboard/settings.py
- requirements.txt
Disable editing, removing and adding event logs and cron logs
Fixes #1253 and Fixes #1325
This adds a second page where you can select the output format(s) for all events
It looks like we can add an export for selecting individual events but I don't know how useful that would be.
When I was in there I saw this issue #1325 that I fixed along with this to disable add/edit of events.
> Add an event log report to the Django admin & Disable editing, removing and adding event and cron logs

- dashboard/common/utils.py
- dashboard/templates/base.html
Hi - I have updated the code to resolve Issue #1347. Let me know if you would like me to change anything!
> Fixes #1347 - Improve Github links on pages

- dockerfiles/Dockerfile
- dockerfiles/Dockerfile.openshift
> Bump `node` images to 16 that were missed previously (#1374)

- config/env_sample.hjson
> issue-1332 added cron query to retrieve Canvas page usage events

- dockerfiles/Dockerfile
- dockerfiles/Dockerfile.openshift
As specified in #1408, to address vulnerability CVE-2021-3973, remove Vim, which was probably installed for debugging purposes.
Closes #1408.
* Start MyLA with `docker compose up --build`
* Access application and perform basic functions
* Check logs for error messages
* *Optional*: Start a shell with `docker compose exec -it web /bin/sh` and verify that Vim is not installed.  E.g.…
* Try running `vi`, `vim-tiny`, etc.
* Use `apt list` to view a list of installed packages and verify that Vim is not included among them
> #1408 - Remove Vim

- dashboard/lti_new.py
> Change the LTI launch message, if user is not a course member

- config/env_sample.hjson
- dashboard/settings.py
- docs/configuration.md
This PR aims to resolve #787.
Test plan:
1) In your `.env` or `docker-compose.yml`, add `ROOT_LOG_LEVEL=DEBUG`, then any additional `env.hjson` keys you'd like to override.
2) Start up the server; note the log messages about overrides.
3) Make sure the new values are being properly used.
> Allow for environment variable override of `env.hjson` values (#787)

- config/cron_udp.hjson
The change removed two unnecessary left joins inside the submission sub-query.
Test Plan:
1. set `ENV_FILE=/secrets/env_udp.hjson`
2. start the cron job: `docker exec -it student_dashboard /bin/bash -c "python manage.py migrate django_cron && python manage.py runcrons --force"`
3. calculate the time spend in submission query with cron log message
I have tested that for 150+ MyLA course ids, this query took about 3mins to finished
> issue_1428 replace left join with join for two tables inside submission query

- dashboard/graphql/objects.py
- dashboard/models.py
- dashboard/views.py
This PR aims to resolve #1430.
> Use `course_date_range` logic for GraphQL course start date (#1430)

- config/cron.hjson
- config/cron_udp.hjson
This PR includes the following query updates:
1. UDW course query returns null value for course id
2. UDP submission query returns unreleased grade for auto graded-submissions
> issue #1435 cron queries update

- assets/src/components/TableAssignment.js
- assets/src/components/Tooltip.js
- assets/src/components/d3/createHistogram.js
- assets/src/components/d3/createProgressBar.js
- assets/src/components/d3/createResourceAccessChart.js
- assets/src/util/createToolTip.js
- package-lock.json
- package.json
Fixes #1367 .
Update to d3-v7 is a breaking change and needed an update to all 3 visuals ( Resource accessed, Grade distribution, Old assignment planning)
- The main change is to the d3.event is deleted but can be accessed as part of the JS events .https://github.com/d3/d3/blob/main/CHANGES.md
- Migration guide to [v6](https://observablehq.com/@d3/d3v6-migration-guide) . I did not see a whole lot of difference to v7 affecting us 
- Updating the [d3-tip](https://github.com/caged/d3-tip) to new library [d3-v6-tip](https://github.com/bumbeishvili/d3-v6-tip#history).  
- The [new library](https://github.com/bumbeishvili/d3-v6-tip#foreword) is based on the old library
-  I don't see the d3-v6-tip updated to v7 but seems to be working fine.
- Assignment planning old needed some changes since it …
> Update the d3 to version7

- dashboard/admin.py
This PR aims to resolve #1411.
> Add `view_on_site` method in course admin (#1411)

- config/cron.hjson
- config/cron_udp.hjson
This is partial revert of cron.hjson change in #1392: restored sis_name, and still leave out the user's name field.
Will file a UDP request for including Canvas user login_id in UDP, so that we can retrieve the sis_name field in UDP cron, too
> issue #1443 added the sis_name retrieval back to user query for UDW cron query

- dockerfiles/Dockerfile
Opted to switch the the library from MariaDB. This doesn't report any security issues in the scan that the other one does. 
You should be able to test this with
`docker scan my-learning-analytics-web` to see that there aren't any more high issues compared to the master branch.
> Fixes #1454 - Switch MySQL Python or system library to version that has less security issues

- dockerfiles/Dockerfile
- dockerfiles/Dockerfile.openshift
* Don't remove libcurl3-gnutls since it's [needed for git.](https://packages.debian.org/bullseye/git)
* Apply changes to Dockerfile.openshift.
> Fixes #1454 (Fix 2) - Switch MySQL to library version with less security issues.

- dashboard/admin.py
This PR aims to resolve #613. See my comment in the issue for rationale behind the solution. I left it so you can still create courses manually in the admin UI, but you can't edit the course ID after you create the course (it'll have to be deleted and re-created).
Resource(s):
- https://docs.djangoproject.com/en/4.1/ref/contrib/admin/
- https://stackoverflow.com/a/46063862
> Disallow changing course canvas ID (#613)

- docker-compose.yml
- dockerfiles/Dockerfile
- dockerfiles/Dockerfile.openshift
- scripts/git_version_info.sh
- start.sh
> Fixes #1462 Move the git commit parsing out of the start.sh and into the build 

- dashboard/cron.py
This PR aims to resolve #1476.
Note that the new `self.valid_locked_str_course_ids` is not used in all cases. There are a number of other usages of `self.valid_locked_course_ids` (with querysets and BQ event queries) where I think integers make sense.
I tested with both UDW and UDP and didn't see any issues. You can test adding a new course by launching one course, starting the cron, and then launching another course during the cron run.
> Fix use of log warning of added courses by creating separate string ID list (#1476)

- assets/src/components/d3/createResourceAccessChart.js
This PR aims to resolve #1190.
To Do
> Make Resources Accessed chart keyboard accessible (#1190)

- dockerfiles/Dockerfile
- dockerfiles/Dockerfile.openshift
This issue is really only coming up in the container service scan, not in the docker scan. 
Running `docker scan` before this does report more issues and dependencies though
Before: Tested 195 dependencies for known issues, found 97 issues.
After: Tested 137 dependencies for known issues, found 67 issues.
Verify that MyLA works as expected.
> Fixes #1482 - Remove additional unused dev dependencies to reduce security impacts

- assets/src/components/d3/createResourceAccessChart.js
- assets/src/containers/ResourcesAccessed.js
- dashboard/settings.py
- dashboard/views.py
Display this limit to the user
I've tested this locally, I need to test if the header works with CORS on the server.
I could have also added this metadata to the JSON but that seems like it would have been a little more work changing the format of the JSON and providing this in the header should work good. 
Okay I tested this out, looks like it works fine.
> Fixes #1466 - Limit display to a configurable number of resources

- assets/src/components/GoogleAnalyticsTracking.js
- assets/src/containers/App.js
- assets/src/globals.js
- assets/src/index.js
- config/env_sample.hjson
- dashboard/templates/base.html
- package-lock.json
- package.json
This PR aims to resolve #1371.
I'll have to run this in one of our test deployments to ensure it's working.
Resources
- https://developers.google.com/tag-platform/tag-manager/web/csp
- https://www.npmjs.com/package/react-ga4
- https://django-csp.readthedocs.io/en/latest/nonce.html
> Move to Google Analytics 4 (#1371)

- dashboard/admin.py
This PR fixes two bugs introduced by my work on PR #1468. It tries to do the following:
- Make courses editable again via the Django Admin interface by modifying the `clean` method in `CourseForm` to only validate `canvas_id` on course creation (`canvas_id` was always left out when editing since it was read only, which lead to errors being thrown).
- Fix a side-effect of the previous change where when a course was edited, subsequent creation of new courses still lableed `canvas_id` as read only. This was fixed by using the `get_readonly_fields` method rather than updating the instance variable.
- Try to improve the validation by disallowing zero and negative Canvas IDs. This wasn't in response to any bugs created by the previous change, but instead exploration of edge cases it makes sense …
> Fix ability to edit courses via the admin and `canvas_id` readonly logic, improve validation (#1509)

- dockerfiles/Dockerfile
- dockerfiles/Dockerfile.openshift
Fixes #1515 
I have updated to `18-bullseye-slim` upon some recommendation from Container service member Erik. 
> 18-bullseye-slim (which is currently in the registry) it's tied to a major version / specific Debian release.
> 
> We have been using 16-slim and alternative for it is 18-slim. it looks like [18-slim refers to Debian 12](https://hub.docker.com/_/node/) at the moment. If you wanted to pin it to that specific Debian release you could use 18-bookworm-slim. (Still might need to be imported to the OpenShift registry; but the idea is you avoid a situation in a couple years where 18-slim suddenly points to Debian 13, possibly breaking stuff.)
I Opted for bullseye as the current python version adaptation. Build are tested on MyLA Beta.  I am happy to change whatever version team …
> I1515 node 18 upgrade

- assets/src/components/d3/createResourceAccessChart.js
Added new visual indicators on resource access page to address accessibility concerns: https://github.com/tl-its-umich-edu/my-learning-analytics/issues/1250
- "Resources Accessed" bars retain the same secondary color from palette settings (blue)~~, with the addition of small white squares as a dotted pattern~~ EDIT: not necessary, as the solid pattern will be distinguishable with the stripes
- "Resources Not Accessed" bars retain the same negative color from the palette settings (gray), with the addition of diagonal black stripes
- Patterns are visually distinct with compliant contrast ratios according to WCAG 2.1 https://www.w3.org/TR/WCAG21/#non-text-contrast
> #1250: Add patterns to Resource Access visualizations

- .github/workflows/main.yml
Fixes #1542 
This PR address following things
1. When a tag is created (via git tag 2017.01.01), auto builds and draft is created as  pre-release. https://github.com/pushyamig/my-learning-analytics/releases/tag/untagged-c851e0a7738c70bbe025
https://github.com/pushyamig/my-learning-analytics/actions/runs/6657871566
3. If user creates a release and publishes it from Github UI, This will trigger creation of tag, Github build is done all good.
https://github.com/pushyamig/my-learning-analytics/releases/tag/1820.01.01
https://github.com/pushyamig/my-learning-analytics/actions/runs/6658577408
4. Now the branches/tags are tagged as `master`, `2023.01.x`, `2023.01.01`
https://github.com/pushyamig/my-learning-analytics/pkgs/container/my-learning-analytics
6.  You can also run any Build manually …
> I1542 GitHub branch fix

- requirements.txt
2.2.0 wasn't building for me on OSX with the latest MySQL client libraries. 2.2.4 builds fine.
> Bump mysqlclient from 2.2.0 to 2.2.4

- dashboard/common/utils.py
I added a statement to replace the .git extension at the end no matter what format it is and ensures that the ssh base still converts to https. This should remove any .git extension from any format of a url when cloning or adding a remote repo. Here is our test plan:
Our test plan is to test four different urls:
- The first test is to clone the repo with a https base url with the .git extension. The expected output is the same url but without the .git extension. This is to ensure that the https base gets the .git extension removed properly with our new code.
- input: https://github.com/tl-its-umich-edu/my-learning-analytics.git
- output: https://github.com/tl-its-umich-edu/my-learning-analytics
- The second test is to clone the repo with a ssh base url with the .git extension. The …
> changes to issue #1358 regarding .git extension

- assets/src/components/AssignmentGoalInput.js
- assets/src/components/AssignmentTable.js
Make unique IDs in Material UI to address the labels pointing to multiple input fields. 
Test plan: Use a screen reader to hover over all input fields ("My Minimum Goal" and multiple "Grade Goal" fields). Each input should have read aloud one singular label associated with it.
> fixes #1592 Screen reader bug - Add Unique Ids to TextFields

- assets/src/components/AssignmentTable.js
Use `id` prop on MaterialUI `InputLabel` component. Results in `aria-labelledBy` properly pointing to the component with the corresponding name:
> fixes #1594 add label names to assignment filter dropdowns

- assets/src/components/AssignmentTable.js
Fixes #1596
if you test this with VO it is not voiced the icon. But I talked with Gonzalo and he checked with NVDA sees to be voicing the label. So he likes the change. (I avoided testing in screen readers since accessibility team don't recommends it)
https://github.com/user-attachments/assets/86eacfe1-7c27-4eb8-b936-e6af0eab4e8b
> #1596 making status icon accessible

- assets/src/components/AssignmentTable.js
Fixes #1598 
The report seems to be requesting `aria-label` `div` for assignment progress bar in the assignment table and tooltip on the Progress bar to provide the same info.
https://github.com/user-attachments/assets/d3706a10-ad24-4a75-a707-d6ed51222276
> #1598 sync the text for aria-label and tooltip

- assets/src/components/AssignmentGoalInput.js
- assets/src/components/UserSettingSnackbar.js
- assets/src/containers/AssignmentPlanningV2.js
Use the debounce package to delay opening the snackbar, also modify the snackbar component to alert screen readers instead of being hidden previously.
> fixes #1589: debounce and read snackbar for assignment planning

- dashboard/settings.py
Fixes #1626 
http://localhost:5001/status/ --> `{"databases": [{"default": {"ok": true}}], "caches": [{"default": {"ok": true}}], "storage": {"ok": true}}`
http://localhost:5001/status/bare_status --> just Returns a status 200 without any o/p response
> #1626 fix watchman status messages

- dashboard/lti_new.py
- dashboard/views.py
Fixes #1624 
Test plan:
open the database and locate the last_access_date field of Course table 
The last_accessed_date can be updated via two routes:
Case 1: 
1. launch MyLA LTI on Canvas
2. notice the last_access_date timestamp is updated for this course
Case 2:
1. go to <myla_url>/courses/<course_id>
2. notice the last_access_date timestamp is updated for this course
> added the lti launch time as the course last_access_date

- .github/dependabot.yml
I locally tested merging these commits on my own fork. You can see the results of enabling grouped updates via these pull requests: https://github.com/jaydonkrooss/my-learning-analytics/pulls
The npm and python dependencies will separately group, and only minor and patch updates are being included.
> 1634: create dependabot yaml file for automatic grouped updates

- dashboard/lti_new.py
Fixes #1631. Just checking is course membership has atleast `instructor` role then giving him the access
"http://purl.imsglobal.org/vocab/lis/v2/membership#Instructor",
With Only instructor role in a course will look like below
```
[
"http://purl.imsglobal.org/vocab/lis/v2/institution/person#Administrator",
"http://purl.imsglobal.org/vocab/lis/v2/institution/person#Instructor",
"http://purl.imsglobal.org/vocab/lis/v2/institution/person#Student",
"http://purl.imsglobal.org/vocab/lis/v2/membership#Instructor",
"http://purl.imsglobal.org/vocab/lis/v2/system/person#User"
]
```
with instructor and TA role will look as below. This combination of role where membership is both instructor and TA are taken as instructor role and thus allow create a course in MyLA Database
```
[ …
```
> #1631 instructor role can enable Myla

- config/env_sample.hjson
- dashboard/settings.py
- raise error when the CANVAS_DATA_ID_INCREMENT value is missing in config file, or not of integer type
- commented out the CANVAS_DATA_ID_INCREMENT setting line in the env_sample.hjson file
> issue_1642 make CANVAS_DATA_ID_INCREMENT as a required configration variable

- assets/config/lti_config_template.json
- dashboard/lti_new.py
Fixes #1631 
TA role is set with below 2 string with course membership. So there is no differentiator if user is TA or Teacher in course via LTI role mapping
```
"https://purl.imsglobal.org/spec/lti/claim/roles": [
"http://purl.imsglobal.org/vocab/lis/v2/membership#Instructor",
"http://purl.imsglobal.org/vocab/lis/v2/membership/Instructor#TeachingAssistant",
]
```
So we are adding new LTI custom variable to Myla called   ` "canvas_course_roles": "$Canvas.membership.roles"` for exact user role in a course: https://developerdocs.instructure.com/services/canvas/external-tools/lti/file.tools_variable_substitutions#canvas.membership.roles
While Custom LTI role check might be sufficient, but I am still checking in LTI role list for course membership ( existing check) and adding on new check …
> #1631 any user with teacher role can enable courses
