dashboard/cron.py
when remove duplicate record from dataframe, keep the first record.
Also added several log message for showing number of rows inserted.
=> issue_2: updated the policy for removing duplicates from dataframe

dashboard/static/css/assign.css, dashboard/static/js/app.js, dashboard/static/js/controllers.js, dashboard/static/js/factories.js, dashboard/templates/assignments.html, dashboard/templates/home.html, dashboard/urls.py, dashboard/views.py, package.json
resorting to main pieces of the assignment view #23 ... 
following this will be assignment progress view
=> Assignment view

dashboard/static/css/assign.css, dashboard/static/js/assign-progress.js, dashboard/templates/assignments.html, dashboard/urls.py, dashboard/views.py
This issue addresses the issue #78 , this issue still work in progress last bit remaining is adding marker denoting current and Max possible grade
=> #78 assignment progress view

Dockerfile, dashboard/cron.py, dashboard/static/css/assign.css, dashboard/static/js/assign-progress.js, dashboard/static/js/controllers.js, dashboard/templates/assignments.html, dashboard/views.py, mysql/init.sql, package.json
1. Rules workflow
2. Bootstrap update ~4.1.3
3. CSS  fixes
4. Handles both courses for pilot
5. Current week workflow and view changes
What remains with this view will be Formatting issues and whatever comes up with the feedback
=> #i16,#i106-addressing the rules flow, bootstrap update

dashboard/static/js/grade_distribution.js, dashboard/views.py
=> Refactor some code in the grades view add additional error handling

dashboard/templates/courses.html, dashboard/templates/home.html, dashboard/urls.py
page. Fixes #177
Still needs some additional fixes.
=> This just gets the courses/<course_id> to work and removes the front

dashboard/templates/base.html, dashboard/templates/home.html
=> Change Header Title Fixes #199

dashboard/templates/base.html
=> Fix Help Link Fixes #217

.eslintrc.json, dashboard/cron.py, dashboard/settings.py, dashboard/static/js/controllers.js, dashboard/views.py
Cleaned up SQL in cron to use f-strings for readability
Fixes #225
=> Fixed up a lot of Codacy issues Fixes #225

mysql/init.sql
#248 
I don't see a burning need to support this for pilot as no students seems to be part of multiple courses. But it was small enough fix to do
=> #248 supporting students in multiple courses

migrations/r_10_22.sql
I know we are not doing any kind of migration but I created a migration directory and all the alter SQL query to 10/22 release
=> #256 alter sql for the 10/22 release with bug fixes

dashboard/views.py
=> #261 assignments are not sorted sometime

dashboard/settings.py
Currently the OpenShift build is failing due to import issue in the `settings.py`. This fix should resolve that.
I tested this fix from my personal branch, So you might see latest as successful in Openshift
=> Build is failing due to some import problems

Dockerfile, dashboard/templates/base.html
=> Add github version to footer

dashboard/static/js/grade_distribution.js, dashboard/templates/grades.html, dashboard/views.py
=> #279 show course with grades more than 100

dashboard/settings.py
=> Only watch default database, not udw

Dockerfile, dashboard/templates/base.html
This reverts commit fcd09e2596167c291f142e211507abc3ffa19aff.
I'm going to do this differently since this doesn't work for openshift.
=> Revert "Add github version to footer (#284)"

Dockerfile, start.sh
=> Switch from dockerize to wait port

dashboard/settings.py
=> Improve the LOGGING block 

.env.sample, README.md, dashboard/admin.py, dashboard/common/db_util.py, dashboard/cron.py, dashboard/models.py, dashboard/settings.py, migrations/r_12_02.sql, mysql/init.sql
This fixes #138 
This is currently in progress as it doesn't use this table yet, it still uses the environment variable. 
Not all of the models are 100% yet either as it was created from a dump.
=> Add database table to store the courses we currently support

dashboard/cron.py
=> Fixing an issue where the method moved but I the refrence didn't change

dashboard/cron.py
=> Ignore null user ids in cron run

dashboard/cron.py, dashboard/static/js/assign-progress.js, dashboard/views.py, migrations/r_12_13.sql, mysql/init.sql
=> #320 getting the avg grade of assignment

.vscode/settings.json, dashboard/models.py, dashboard/urls.py, dashboard/views.py, mysql/init.sql
Also fixes a few other pylint issues that I'd found and an issue with
the default SQL mapping
Fixes #332
=> Provide a JSON feed for the courses supported

.env.sample, dashboard/models.py, dashboard/settings.py, dashboard/static/js/file_access_within_week.js, dashboard/urls.py, dashboard/views.py
=> Files visualization needs to account for full number of weeks in term

dashboard/views.py
=> Support jsonp in courses enabled

dashboard/static/js/app.js, dashboard/static/js/controllers.js, dashboard/static/js/factories.js, dashboard/static/js/file_access_within_week.js, dashboard/templates/view_file_access_within_week.html, dashboard/views.py
#376, Making the call that save the default as PUT instead of GET. Followed the guidelines prescribed by Django doc
https://docs.djangoproject.com/en/2.1/ref/csrf/#acquiring-the-token-if-csrf-use-sessions-or-csrf-cookie-httponly-is-true
=> #376 making the set default calls as PUT

.env.sample, dashboard/settings.py, dashboard/urls.py
=> All API urls should have client side caching enabled

.env.sample, dashboard/cron.py
Reverts tl-its-umich-edu/my-learning-analytics#379
I may have done this in the wrong direction.
=> Revert "Update with latest branch"

dashboard/urls.py
=> Remove root page from cache

start.sh
Also remove the nothreading option as it works fine without.
Fixes #339
=> Missing $ in startup script breaks ptvsd

dashboard/urls.py
=> Removing private urls from caching for now

dashboard/admin.py, dashboard/models.py
=> Improve the courses admin view to display more details in the columns

dashboard/cron.py
=> Issue - 389 - Add total bytes billed for BQ call to cron logs

.env.sample, .eslintrc.json, .gitignore, .vscode/launch.json, README.md, dashboard/cron.py, dashboard/static/js/d3.legend.js, dashboard/static/js/file_access_within_week.js, dashboard/static/js/grade_distribution.js, dashboard/templates/view_file_access_within_week.html, dashboard/urls.py, docker-compose.yml, manage.py, requirements.txt, start.sh
Noticed that there were undeclared/unused variables in the JavaScript files, so I fixed them. 
I intentionally didn't touch `app.js`, `assign-progress.js` and `controllers.js` - I'll fix it after https://github.com/tl-its-umich-edu/my-learning-analytics/pull/377 lands.
=> Added eslint config, fixed undeclared var and removed unused var

.env.sample, Dockerfile, dashboard/settings.py, docker-compose.yml
=> Allow configuring container timezone

.env.sample, README.md, dashboard/lti.py, dashboard/settings.py, dashboard/urls.py, requirements.txt
- Auto creates user auth accounts if needed
- Doesn't create course records or modify course view options
Related #266
=> Add basic LTI 1.1.1 support

assets/src/components/HorizontalBar.js, assets/src/components/d3/createHorizontalBar.js, assets/src/containers/AssignmentPlanning.js
Hard-coded the horizontal bar width and height, fixes strange bug with bar sizing changing randomly.
=> Assignment bug fix

.env.sample, dashboard/cron.py, dashboard/settings.py
=> Improve BQ call to return multiple courses

assets/src/containers/AssignmentPlanning.js, assets/src/containers/FilesAccessed.js, assets/src/containers/GradeDistribution.js, assets/src/hooks/useFetch.js
Fixes https://github.com/tl-its-umich-edu/my-learning-analytics/issues/432
Especially useful for handing multiple calls to `useFetch` on one page - with this implementation, user can be informed while new data is being fetched.
=> Refactored useFetch to return tuple

dashboard/static/js/file_access_within_week.js
=> issue #444 update the background color for unread files

dashboard/common/db_util.py, dashboard/common/utils.py, dashboard/static/js/file_access_within_week.js, dashboard/views.py
updated the student count for percentage calculation, based on grade range selection. Fixes #443
=> issue #443 update the student count according to grade selection

dashboard/cron.py, dashboard/views.py
=> #450 handling weighted assignments groups with no assignments yet

.env.sample, .vscode/launch.json, README.md, dashboard/settings.py, manage.py, requirements.txt, start.sh
Fixes issue 452
Also adds better checking for the start script for whether variables are
set to True/False or empty
=> Issue 453 - PTVSD debug mode no longer works

dashboard/admin.py
=> Issue 452 - Saving new course with all options selected doesn't save any

.env.sample, .vscode/launch.json, LICENSE, NOTICE, README.md, dashboard/admin.py, dashboard/common/db_util.py, dashboard/common/utils.py, dashboard/context_processors.py, dashboard/cron.py, dashboard/models.py, dashboard/settings.py, dashboard/static/js/file_access_within_week.js, dashboard/templates/base.html, dashboard/views.py, manage.py, requirements.txt, start.sh
I had some issues when checking out react branch due to environment variables changes (mostly UDW -> DATA_WAREHOUSE and canvas id prefixing to increment changes). This is just to pull master changes in so there are less issues switching dev branches
=> Merging master changes into react

dashboard/admin.py
=> When adding a course in admin non numeric id results in 500 error

dashboard/admin.py, dashboard/models.py, dashboard/templates/base.html, dashboard/views.py
=> Merging the master changes to react

dashboard/cron.py, dashboard/migrations/0001_initial.py, dashboard/models.py, dashboard/views.py
=> Issues with file_access and other tables after initial migration

README.md, manage_ptvsd.py
Added a separate manage.py to be able to run the cron script
=> PTVSD for cron no longer works

.env.sample, dashboard/cron.py, dashboard/settings.py
Work done at hackathon to remove umich ed_app from query and pull into a config value.
=> Removing umich specificity from bq query

dashboard/views.py
=> Fixes #521 - Files view is not showing files I've viewed for logged in

assets/src/__tests__/d3/__snapshots__/createHistogram.test.js.snap, assets/src/__tests__/util/array.test.js, assets/src/__tests__/util/math.test.js
Continual work addressing https://github.com/tl-its-umich-edu/my-learning-analytics/issues/426.
=> Updated snapshots and added more tests

assets/src/containers/App.js, assets/src/containers/AssignmentPlanning.js, assets/src/containers/FilesAccessed.js, assets/src/service/api.js
=> Removing localhost for relative URLs

assets/src/containers/FilesAccessed.js
#549 . I think I broke this some point and fixed it here
=> #549 fix for working in FF

.vscode/settings.json, assets/src/components/GoogleAnalyticsTracking.js, assets/src/containers/App.js, assets/src/containers/Course.js, assets/src/containers/CourseList.js, assets/src/index.js, assets/src/routes/routes.js, dashboard/templates/base.html, package.json
- GoogleAnalyticsTracking component will track page views when initialized and every time the route is changed
- refactored how routers/routers are setup so there is only one router in the application (app is now the main routing entry point which can have components added like CourseList and the new Course)
- Note: static standalone pages are not currently tracked (ex: login page which will eventually be converted to a react page)
closes #470
=> Add google analytics to react

assets/src/containers/DashboardAppBar.js, dashboard/rules.py, dashboard/urls.py, dashboard/views.py
Fixes both #565 #568
- removed template rules that are not relevant
- add the URL for `/courses/` from UI just for visibility for testing but can also be added #552 
@andrew-gardener if you could review this by end of today we can merge it and have it ready for testing here at umich
=> #568 #568 bug fixes with django rules/react branch changes

README.md, manage_ptvsd.py
merging the master changes to react branch
=> master to react

assets/src/containers/CourseList.js
=> Removed "the welcome page"

assets/src/routes/routes.js
=> Reorder views

assets/src/components/Table.js, assets/src/containers/GradeDistribution.js
=> Removed border from grade distribution table

assets/src/__tests__/util/object.test.js, assets/src/containers/IndexPage.js, assets/src/util/object.js
=> Added error message if no views are active

Dockerfile, assets/src/__tests__/util/math.test.js, assets/src/containers/DashboardAppBar.js, assets/src/containers/GradeDistribution.js, assets/src/util/math.js, start.sh
=> Added median grade to Grade Distribution view

assets/src/components/AvatarModal.js, assets/src/components/Table.js, assets/src/containers/App.js, assets/src/containers/Course.js, assets/src/containers/CourseList.js, assets/src/containers/DashboardAppBar.js
Addresses #552.
To test, the user that is logged in must be in more than one course. Replace the `user` object in `App.js` with the following to test:
```js
const user = Object.freeze({
username: myla_globals.username,
admin: myla_globals.is_superuser,
enrolledCourses: [
{ course_id: 231768, course_name: 'EECS 808 008 FA 2057' },
{ course_id: 123456, course_name: 'Some Other Course' },
{ course_id: 678901, course_name: 'Yet Another Course' }
],
isSuperuser: myla_globals.is_superuser,
isLoggedIn: !!myla_globals.username
})
```
=> Avatar change course

assets/src/containers/Course.js, assets/src/containers/FilesAccessed.js
Grades and Assignment views have the `disabled` prop - Files view now also relies on the `disabled` prop.
=> Made the disabled message consistent in Files Accessed view

assets/src/containers/ResourcesAccessed.js, config/env_sample.json, dashboard/common/utils.py, dashboard/context_processors.py, dashboard/models.py, dashboard/settings.py, dashboard/templates/base.html, dashboard/views.py
This PR address the flow of sending a course the resource type the course has via `/info` api call
```
{  
"canvas_id":2922222,
"term_id":17700000000000111,
"name":"DENT 225 201 SU 2019",
"term":{  
"id":17700000000000111,
"canvas_id":111,
"name":"Spring/Summer 2019",
"date_start":"2019-05-07 00:00:00+00:00",
"date_end":"2019-12-31 00:00:00+00:00"
},
"current_week_number":12,
"total_weeks":16,
"course_view_options":{  
"fa":1,
"ap":1,
"gd":1
},
"resource_types":[  
"Files",
"Videos"
]
}
```
=> sending the course resource type via info api

assets/src/containers/ResourcesAccessed.js, dashboard/templates/base.html, dashboard/views.py
**One Resource Type**
**More Than One Resource Type**
=> Updated Checkbox logic

assets/src/containers/ResourcesAccessed.js
=> Added message that shows up when course only has one resource type

dashboard/cron.py, dashboard/views.py
=> #578 fixes showing incorrect graded assignment in view

assets/src/containers/CourseList.js
=> "the welcome page" snuck in again somehow

assets/src/components/UserSettingSnackbar.js, assets/src/containers/GradeDistribution.js
This component can now be used for any view that allows users to set their preferences.
=> Extracted the Snackbar component for user setting

assets/src/__tests__/containers/assignments.view.test.js, assets/src/__tests__/testData/assignmentViewTestData.js, assets/src/containers/AssignmentPlanning.js, dashboard/views.py
=> #579 assignments now scrolls to current week row

dashboard/settings.py
#631 
This error is happening since new properties are added as part of the resources view defaulting to files resources to escape of no configuration error
=> #631 adding default resources property

dashboard/views.py
Returns an empty array instead of "no data" message
=> Fixes #533 Files accessed view keeps showing loading spinner

CONTRIBUTING.md, README.md
Addresses #604 
Added a "Getting Started" section to the README and created a new CONTRIBUTING guide. 
Can we share the `myla_test_data` sql file? 
This is just a draft - please feel free to make suggestions/changes.
=> Changes to README and new CONTRIBUTING doc

CONTRIBUTING.md, README.md, assets/src/components/AvatarModal.js, assets/src/containers/App.js, dashboard/templates/base.html
Merging master changes to 2019.02.x branch
=> 2019 02.x merge

config/env_sample.json, dashboard/rules.py, dashboard/settings.py, dashboard/views.py
Fall branch merge for issue #687 and PR #699.
=> Issue 687 (#699)

assets/src/routes/routes.js
Resolves #573.
Merge conflict must have been resolved incorrectly in the past, making this PR necessary again.
=> Reordered views

assets/src/containers/AssignmentPlanning.js, assets/src/containers/ResourcesAccessed.js
Fixes #725
1. I have refactored the code and used the same naming convention for hook as in AssignmentPlanning view for making it easier to understand login in both views.
2. Added the Snackbar, separated the get/set default logic outside of `ResourcesAccessed.js` as in `AssignmentPlanning.js`
3. once thing I did not do is the content call is still inline in `useEffect` instead of `api.js`. I felt it can be handled separately as the logic is different from Assignment view
=> Fixing the disappearing slider when defaults set

assets/src/components/Tooltip.js
=> Changed due to due at

Dockerfile
=> Fixes #759 - Re-do Dockerfile to avoid directly pulling in previous

dashboard/templates/base.html
This PR addresses issue #753 by removing the duplicate Google Analytics ID in base.html.
=> Removed Duplicate Google Analytics ID in base.html

assets/src/components/d3/createResourceAccessChart.js
This PR fixes typographical issues and addresses suggestions from PR #777 and closes issue #724 .
=> Fixed Typos in Tooltips

dashboard/models.py
Since this message only shown when user has not set defaults for views, this change does:
1. Downgrade the logging level to DEBUG
2. Rewrite of the log message
=> issue #776 downgrade the logging level to INFO

README.md
Resolves #795
Redirected link to `Resources Accessed` page.
=> Fixed broken link to old files accessed help

README.md
remove links in the README to specific courses  for issue #810
=> update read.me (remove unaccesible links)

docker-compose.yml
I don't have any metrics yet on this but reading about it seems like this should be the best performance. I tried modifying the code and it was fast to update and feels pretty good using it.
=> Improve docker-compose file system performance - Fixes #767

assets/src/components/d3/createResourceAccessChart.js
=> #836 fixing the filename shifting position when scrolling

assets/src/components/d3/createResourceAccessChart.js
=> #837 making the resource name longer

assets/src/containers/GradeDistribution.js
=> #895 grades legend change

dashboard/cron.py, dashboard/settings.py
I removed the processid from the log message because it doesn't seem to be useful to me. We could add it back in. I'm testing this out really quick.
=> Fixes #865 - Cron except should be logged as exception

dashboard/views.py
=> #857 insufficient grades count won't shown the view

dashboard/urls.py
=> Adding trailing slash with course_enabled url

dashboard/views.py
This PR changes the percentages in Resource Accessed so that the appear as whole numbers. Addresses issue #905.
=> Percents in Resource Accessed Should Be Whole Numbers (#905)

assets/src/containers/IndexPage.js
=> Fixed overflow in IndexPage

.gitattributes
=> #928 adding .snap file as binaries in .gitattributes

README.md, cypress/integration/myla/__snapshots__/basic_test.js.snap
Fixes #933 
1. I have updated the readme with more info about cypress test
2. I also updated the snapshot since the latest changes from the master from the resource view. 
Currently, we don't have a process to automate the snapshot test. With the Jest unit test if a test fails we need to update the snapshots. 
Let me know what others think of updating the snapshots.
=> #933 readme about cypress tests and snapshot update

assets/src/components/AssignmentGoalInput.js
Fixes #906 
Adjust the css to make the field wide enough to fit the current error
text.  Not an optimal fix but works since I failed to figure out how to
get the material style to behave better.
=> Fixes #906

assets/src/__tests__/components/__snapshots__/AssignmentGradeBoxes.test.js.snap, assets/src/__tests__/components/__snapshots__/Label.test.js.snap, assets/src/__tests__/components/__snapshots__/Line.test.js.snap, assets/src/__tests__/components/__snapshots__/ProgressBarV2.test.js.snap, assets/src/__tests__/util/assignment.test.js, package.json
#943 
Steps taken to fix the tests:
1. Adding `react-test-renderer` module to `package.json`
2. Updating the snapshots for the tests that failed due to missing module `react-test-renderer`
3. for the test `calculateAssignmentGradeFromCourseGrade` looks to me like the `expected` values were wrong so I have updated based on the `actual `
=> #943 fixing Jest test for assignment redesign

CONTRIBUTING.md, README.md
Move jest documentation from CONTRIBUTING.md to README.md
=> Move jest doc fixes #939

Dockerfile, requirements.txt
Fixes #950 
I tested the cron and application launches fine.
=> #950 upgrade to python3.8

Dockerfile
=> Re-add git to Dockerfile as it's not found

assets/src/routes/routes.js, config/env_sample.json, dashboard/views.py
=> Supporting global view disable

assets/src/containers/App.js, assets/src/globals.js, dashboard/common/db_util.py, dashboard/common/utils.py, dashboard/context_processors.py, dashboard/lti_new.py, dashboard/settings.py
Fixes #1009 
Now supports become user and course links from myla for admins.
=> #1009 fix for become_user and course links

dashboard/cron.py, dashboard/models.py
Fixes #1017
Co-authored-by: chrisrrowland <chris.robert.rowland@gmail.com>
=> Course_id still in resource table after being dropped by conversion

.vscode/settings.json
=> Enable mypy type hinting for VSCode

dashboard/cron.py
Fixes #1025.
**_NOTE:_** I recommend you tell GitHub to ignore whitespace when you view the diffs of this PR.  I changed just a few lines of code, but also indented a block of code to be inside a conditional.  GitHub's diff shows this as a big change unless whitespace is ignored.  (I wish Python used brackets!)
This change skips over converting `user_login_name` to `user_id` during the ETL's event query processing if the name column isn't available.
=> Warn about old queries, but support them (#1025)

assets/src/containers/Course.js
=> #1004 403 error message wording change

dashboard/views.py
=> #1050 assigments with no due date will show up

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
Changed H2 to H3 to better fit in the issue.
Reduced the bug expected behavior of description text.
=> Update issue templates to reduce the size of text and make issues fit better

dashboard/lti_new.py
Fixes #1043 
I am having the message shown with 'lti_error` along with it. @jennlove-um is fine with this
With this issue #1003, I might refactor showing error user facing vs configuration issues during local development
=> i1043_student_view_message

assets/src/containers/Course.js, dashboard/rules.py
Additionally allow access to get_course_info if a course is not loaded
(per null term hack)
Closes #1046
=> Improved message when course not loaded

assets/src/components/AvatarModal.js, assets/src/containers/App.js, dashboard/common/utils.py, dashboard/settings.py
Fixes #1079
This issues removes the logout URL from the UI doesn't send in the Login URL when LTI. But this should be available with SAML/local 
This PR is based off of #1079 1073
=> Issue 1079 remove login logout lti

config/env_sample.json
=> Updating settings to reference the expectation for the LOGOUT URL

assets/src/components/AssignmentTable.js, assets/src/components/PopupMessage.js, assets/src/components/ProgressBarV2.js
Fixes #799 adds a property to ProgressBarV2 for descriptions.
AssignmentTable constructs and passes a description.
=> Make asignment grade progress bar accessible

assets/src/__tests__/components/__snapshots__/AssignmentGradeBoxes.test.js.snap, assets/src/__tests__/components/__snapshots__/ProgressBarV2.test.js.snap, assets/src/components/AssignmentGoalInput.js
Fixes #1112 
This is how it Looks now
Before
=> #1112 changing the Goal component names

assets/src/containers/DashboardAppBar.js
=> Making top navigation fixed

assets/src/components/AssignmentTable.js, assets/src/containers/AssignmentPlanningV2.js, assets/src/util/assignment.js
Closes #1114 
Fixes #1139
Replace graded only filter with assignment status filter
Add clear filters button
Status icons for all 3 states, color scheme to match progress bar scheme
Column names and filter text adjusted
=> Requirements updates for Assignment Planning V2 filters.

assets/src/components/AssignmentTable.js
=> Reenable Scroll to current week

.dockerignore
=> Updating docker ignore to ignore SQL and a few more file extensions.

assets/src/components/AssignmentTable.js, assets/src/util/assignment.js
Change 'Not Yet Graded' to 'Pending Grade'
Change "X" icon on clear filter button to "Clear Filters" text
Add an alert banner to say "No assignments match your filter selections" when no assignments match the selected filters.
=> Ap2 feedback

dashboard/lti_new.py
Fixes #1153.
Replace an old reference that had crept back in while resolving conflicts that arose while working on other issues.
=> Fix config error in JWK code (Issue #1153)

assets/src/components/AssignmentGoalInput.js, assets/src/components/AssignmentTable.js, assets/src/containers/AssignmentPlanningV2.js, assets/src/hooks/useSaveUserSetting.js, assets/src/hooks/useSyncAssignmentAndGoalGrade.js, assets/src/hooks/useUserAssignmentSetting.js, assets/src/util/assignment.js, assets/src/util/object.js, dashboard/graphql/mutation.py
Fixes #877, Refactor of Event Logging, Now only sending what changed as part of user action instead of log of changes
=> #877 refactoring event logging

package.json
=> #1184 fixes the docker build failure

dashboard/cron.py, requirements.txt
Fixes #746 - Prints error and fails is there is an error in query
Also updates bigquery library to latest version with pandas support
=> Fixes #667 - In cron access denied to bigquery should be an error.

dashboard/settings.py
=> Add help url for Assignment Planning v2

docker-compose.yml
=> Missing dockerfile for webpack_watcher

dashboard/settings.py
=> #1197 assignment goal plan url

assets/src/components/SurveyModal.js, assets/src/containers/DashboardAppBar.js, assets/src/globals.js, dashboard/common/utils.py, dashboard/settings.py, requirements.txt
* Adding constance for dynamic config
* Conditinally showing survey link based on config
Fixes #1107
=> Adding adding survey button to top menu

config/env_sample.json
=> update comments for LTI config in env.json (iss: #1223)

README.md, assets/src/__tests__/components/__snapshots__/AssignmentGradeBoxes.test.js.snap, assets/src/__tests__/components/__snapshots__/ProgressBarV2.test.js.snap, assets/src/components/AvatarModal.js, assets/src/containers/CourseList.js, assets/src/containers/DashboardAppBar.js, assets/src/globals.js, dashboard/common/utils.py, dashboard/lti_new.py
Uses user's full name instead of username and initials instead of first letter of username (will fallback to username if name is blank)
Also updates first name, last name, and email on LTI launches (to sync changes over time)
Closes #1226
=> Add friendlier display name

dashboard/cron.py
this is to revert [PR #1233](https://github.com/tl-its-umich-edu/my-learning-analytics/pull/1233)
=> revert prior changes to issue_1208

assets/src/util/assignment.js, dashboard/cron.py
(issue_1208 address the display problem of graded but grade not released submission)
Fixes #1208.
=> fix submission graded display, but grade not released (iss. #1208)

CONTRIBUTING.md, README.md, docker-compose.yml, dockerfiles/README.md, requirements.txt
Resolves #1252.
After much research and testing, I decided to go with Django 3.1.7.  It appears to be the latest version available and it's one higher than highest version suggested by @dependabot.  I was cautiously thinking that we should only use the most recent version of 3.0.x, but MyLA seems to work well with 3.1.7.
While working on this issue, I found that MyLA's docker-compose.yml installed MySQL 5.7.22 although my DB was already configured to work with 5.7.26.  There are some changes between 22→26 that cause the older MySQL to complain about using a newer DB.  After discussion with @jonespm, we agreed it would probably be safe to specify the more generic 5.7.
At this time, the version of MySQL installed was 5.7.33.  MySQL's log contained warnings like:
```txt
InnoDB: Table …
```
=> upgrade Django and local dev. MySQL (iss. #1252)

assets/src/util/assignment.js, dashboard/cron.py
=> fix display of submission graded, not released (iss. #1208)

dashboard/views.py
To test: 
Install MyLA tool in two courses which has at least one enrolled student in common. Log in with as that student, and make sure no duplicated resource access event shown in the resource_access view.
=> issue-1276 added the check for resource and user course_id in the resource access view

dashboard/views.py
- fixed the missing space error in the resource access query
- changed the resource access query as f-string
=> Issue 1276 - changed the resource access query as f-string

dashboard/models.py
Hi - here is a pull request for issue 1198 - please let me know if you would like me to update anything. Thank you!
=> Fixes #1198 - Increase detail for missing start/end date

config/env_sample.hjson, dashboard/settings.py
=> issue_1359 updated the default value for DJANGO_DEBUG settings

dashboard/lti_new.py
=> issue_1365 update LTIError to lti_error

dashboard/views.py, docker-compose.yml
#1378 combined resource id with resource name as index.
We can concatenate resource id with resource type, that would be unique identifier and can be used as data frame index.
=> Fixes #1378 Resources Accessed does not load when the course contains files with a semicolon in the filename

dashboard/views.py
Fixes #794
This PR is expanding on the @vjcao PR #808. His suggestion to make the last few low-performing grades close to the rest of the distribution is valid. 
@vjcao Thanks for the change, and it took some time to get back to this PR. Your commit is added authored as you and based on some more testing minor changes are made on top of it. we will close that PR once this get merged. 
I put this change on MyLA Beta for @jennlove-um to take a look since wanted to see how this will work across various distributions. She seems to be happy with the change.
=> #794 Fix outlier detection Logic

dashboard/cron.py, dashboard/models.py
This is going to need to be refactored after #1423. So I'm leaving as a draft for now.
=> Fixes #1327 - Improve verify_course_ids to only consider courses with local data

assets/src/components/d3/createResourceAccessChart.js
Fixes #1437 
This course has all 3 type of resources: pages, videos, files: 563654
=> #1437 fixing the broken link for resources accessed view

assets/src/components/SelectCard.js
This PR aims to resolve #1473.
=> Use layering approach to fix keyboard access to view, improve screenreader text (#1473)

assets/src/components/SelectCard.js
This PR aims to resolve #1494.
=> Change `class` prop to `className` in `SelectCard` (#1494)

config/cron.hjson, config/cron_udp.hjson, dashboard/cron.py
Also Fixes #1432 - May need to make America/Detroit in cron config configurable
=> Fixes #1484 - MyLA importing incorrect timezone times

config/cron_udp.hjson
=> issue_1504 update the course cron query

config/cron_udp.hjson
Added comment into the cron_udp.hjson file
=> issue_1502 added comment inside cron file for the data freshness date indicator

assets/src/containers/GradeDistribution.js, assets/src/util/object.js, dashboard/settings.py, dashboard/views.py
=> limiting GD view based on course enrollment

assets/src/components/AssignmentGoalInput.js, assets/src/containers/AssignmentPlanningV2.js, assets/src/hooks/useMathWarning.js
Fixes #1497 
Test Plan
https://docs.google.com/spreadsheets/d/1fOLY2byRBUZ1JzCFir6WiIPfrMPN2_-7oJKr5zhsiEM/edit#gid=0
=> #1497 fix error message when all assignments are graded

assets/src/hooks/useMathWarning.js
Fixes #1497 
Updated the test plan: https://docs.google.com/spreadsheets/d/1fOLY2byRBUZ1JzCFir6WiIPfrMPN2_-7oJKr5zhsiEM/edit#gid=2106880085
The alert message logic is around when assignments grades (all ,few, none) and assignment goal grade set by user (all , few none)
=> #1497 fixes msg around assignments are graded and all goals are set

Dockerfile
=> #1513 updating python/node base to bookworm

.github/workflows/main.yml, start.sh
Fixes #1578
Logging is happening to console
Changes from this PR are added to Myla Beta, but can also be tested from locally. Just use a Proxy like ngrok or loophole
https://docs.gunicorn.org/en/stable/settings.html#access-log-format
=> I1578 having Gunicorn log the IP address

assets/src/components/GoogleAnalyticsTracking.js, assets/src/containers/App.js, assets/src/globals.js, assets/src/index.js, config/env_sample.hjson, dashboard/common/utils.py, dashboard/settings.py, dashboard/urls.py, dashboard/views.py, package-lock.json, package.json
I accidentally directly committed to master
=> undo direct commits

assets/src/components/AssignmentTable.js
Fixes #1591 
The test plan is described in the Issue description.
=> #1591 Lock Goal now has a Label

assets/src/components/AssignmentGoalInput.js
=> issue #1595 button label change

assets/src/components/ProgressBarV2.js, assets/src/containers/AssignmentPlanningV2.js
=> #1597 improving aria-label function by removing tab index on progress bar

docker-compose.yml
=> #1612 remove Docker compose version

dashboard/settings.py
Fixes #1626 
http://localhost:5001/status/ - > `{"databases": [{"default": {"ok": true}}], "caches": [{"default": {"ok": true}}]}`
http://localhost:5001/status/bare_status: return 200 OK
=> I1626 watchman err fix

Dockerfile
=> Upgrade Python 3.11. Fixes #1635
